name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Fetch all history for all tag and branches
      run: git fetch --prune

      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - run: |
        dotnet --version
        
    - name: Install git version
      uses: ./gitversion/setup
      with:
        versionSpec: '5.3.x'
        
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: ./gitversion/execute
    - run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
