name: Yaml Lint
on:
  push:
    branches: [ master ]
    tags: 
      - "v*"
  pull_request:
    branches: [ master ]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: actions/checkout@v1
