name: .NET Core

on:
  push:
    branches: [ master ]
    tags: 
      - "v*"
  pull_request:
    branches: [ master ]

jobs:
  build_test_version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    
    - name: Fetch all history for all tag and branches
      run: git fetch --prune 

      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - run: |
        dotnet --version
                       
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  
  sonar_scanner:
    needs: build_test_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for scanning
        uses: actions/checkout@v1

      - name: Checking MSBuild
        run: |
          export SONAR_SCANNER_VERSION=4.4.0.2170
          export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
          curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          export PATH=$SONAR_SCANNER_HOME/bin:$PATH
          export SONAR_SCANNER_OPTS="-server"


          
      - name: Install git version
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
         versionSpec: '5.2.x'

   
   
