name: .NET Core

on:
  push:
    branches: [ master ]
    tags: 
      - "v*"
  pull_request:
    branches: [ master ]

jobs:
  My-Task:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team and Persons"
      uses: rowi1de/auto-assign-review-teams@master
      with:
        repo-token: ${{ secrets.MYGITHUB_TOKEN }}
        teams: "gitub-org-team"         # only works for GitHub Organisation/Teams
        persons: "abhithakre"              # add individual persons here 
        include-draft: false            # Draft PRs will be skipped (default: false)
        skip-with-manual-reviewers: 0   # Skip this action, if the number of reviwers was already assigned (default: 0)
